routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Auth','prefix' => 'thanh-vien'], function(){
    Route::get('dang-ky','RegisterController@getFormRegister')->name('get.user.register'); // đăng ký
    Route::post('dang-ky','RegisterController@postRegister')->name('post.user.register'); // xử lý đăng ký

    Route::get('dang-nhap','LoginController@getFormLogin')->name('get.user.login'); // đăng nhập
    Route::post('dang-nhap','LoginController@postLogin')->name('post.user.login'); // xử lý đăng nhập

    Route::get('dang-xuat','LoginController@getLogout')->name('get.user.logout'); // đăng xuất

});


Route::get('/', 'HomeController@index')->name('client.home');
Route::get('/product/{id}', 'ProductController@detail')->name('client.product_detail');
Route::get('/contact', 'ContactController@create')->name('client.contact_create');
Route::post('contact', 'ContactController@store')->name('post.contact');
Route::get('/about', 'PageController@about')->name('client.about');
Route::get('/shopping-guide', 'PageController@shoppingGuide')->name('client.shopping_guide');
Route::get('/policy', 'PageController@policy')->name('client.policy');
Route::get('/login', 'LoginController@create')->name('client.login_create');
Route::get('/category_product/{id}', 'ProductCategoryController@detail')->name('client.category_producte_detail');
Route::get('search', 'HomeController@search')->name('client.search');
Route::get('/info/user', 'InfoUserController@index')->name('info.user');
Route::post('/update/info/user', 'InfoUserController@updateInfoUser')->name('update.info.user');
Route::get('list/order/transported', 'InfoUserController@listOrderTransported')->name('list.order.transported');
Route::get('cancel/order/{id}', 'InfoUserController@cancelOrder')->name('cancel.order');
Route::get('list/order/success', 'InfoUserController@listOrderSuccess')->name('list.order.success');
Route::get('/billing/{id}', 'BillingController@billing')->name('billing');
Route::get('/change/password', 'InfoUserController@getFormChangePasswor')->name('change.password');
Route::post('/change/password', 'InfoUserController@changePassword')->name('change.password');

Route::get('don-hang.html','ShoppingCartController@index')->name('get.shopping.list'); // gio hang
Route::prefix('shopping')->group(function () {
    Route::get('add/{id}','ShoppingCartController@add')->name('get.shopping.add'); // thêm giỏ hàng
    Route::get('delete/{id}','ShoppingCartController@delete')->name('get.shopping.delete'); // xoá sp trong gi hàng
    Route::get('update/{id}','ShoppingCartController@update')->name('ajax_get.shopping.update'); // cập nhật
    Route::get('info/payment', 'ShoppingCartController@getFromPayment')->name('get.info.payment');
    Route::post('pay','ShoppingCartController@saveOrder')->name('post.shopping.pay'); // xử lý giỏ hàng lưu thông tin
    Route::get('delete-all','ShoppingCartController@deleteAll')->name('get.shopping.delete_all'); // xử lý giỏ hàng lưu thông tin
});

Route::namespace('Admin')->prefix('admin')->middleware(['auth'])->group(function () {
    Route::middleware(['is_admin'])->group(function () {
        Route::get('/', 'DashboardController@index')->name('admin.dashboard');
        Route::resource('product', 'ProductController')->except(['show']);
        Route::resource('order', 'OrdersController');
        Route::get('order/pack/{flg}', 'OrdersController@pack')->name('order.pack');
        Route::get('order/deliver/{status}', 'OrdersController@deliver')->name('order.deliver');
        Route::delete('order/cancel/{order_id}', 'OrdersController@cancel')->name('order.cancel');
        Route::post('update/shiper/{id}', 'OrdersController@updateShiper')->name('order.shiper.status');
        Route::post('update/status/{id}', 'OrdersController@updateStatus')->name('order.update.status');
        Route::resource('category_product', 'CategoryProductController')->except(['show']);
        Route::resource('supplier', 'SuppliersController')->except(['show']);
        Route::resource('information', 'InformationsController')->except(['show']);
        Route::resource('user', 'UsersController')->except(['show']);
        Route::get('/contact', 'ContactsController@index')->name('contact.index');
        Route::delete('contact/destroy/{id}', 'ContactsController@destroy')->name('contact.destroy');
        Route::get('update/confirm/{id}', 'OrdersController@updateConfirm')->name('order.update.confirm');
    });
    Route::middleware(['is_role_access'])->group(function () {
        Route::resource('order', 'OrdersController')->except(['show']);
    });
});
Auth::routes(['register' => false]);
Route::get('/logout', 'Auth\LoginController@logout')->name('auth.logout');
Route::get('admin/logout', 'Auth\LoginController@logoutAdmin')->name('auth.admin.logout');
Route::post('admin/login', 'Auth\LoginController@postAdminLogin')->name('auth.admin.login');
Route::get('/home', 'HomeController@index')->name('home');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Order extends Model
{
    const STATUS_ORDER = [
        0 => 'Đang đóng gói',
        1 => 'Đã đóng gói',
        2 => 'Đang giao',
        3 => 'Đã giao',
        4 => 'Đã hủy',
        5 => 'Khách không nhận'
    ];
    public $table = "donhang";
    protected $fillable = [
        'TrangThai', 'XacNhan'
    ];

    public function user()
    {
        return $this->belongsTo(User::class,'id_ND');
    }

    public function user_shiper()
    {
        return $this->belongsTo(User::class,'id_NV');
    }

    public function donated()
    {
        return $this->hasOne(Donated::class, 'id_DH', 'id');
    }

    public $timestamps = false;
}

app/Http/Controllers/Admin/OrdersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Order_Detail;
use Illuminate\Http\Request;
use App\Order;
use App\User;
use App\Product;
use Illuminate\Database\Eloquent\Model;

class OrdersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        if (\Auth::user()->VaiTro == 2) {
            return redirect()->route('order.pack', 0); 
        }
        $menu = '';
        $status = Order::STATUS_ORDER;
        $orders = Order::with('user:id,Ten,DiaChi,SDT');

        if($request->menu == 'success') {
            $menu = $request->menu;
            $orders->whereIn('TrangThai', [3,4,5]);
        } else {
            $orders->whereIn('TrangThai', [0,1,2]);
        }

        if($request->name) {
            $orders->where('Ten','like', '%'.$request->name.'%');
        }

        if($request->status) {
            $orders->where('TrangThai', $request->status);
        }
        if($request->employee_id) {

            if($request->employee_id == 'null') {
                $orders->whereNull('id_NV');
            } else {
                $orders->where('id_NV', $request->employee_id);
            }

        }

        $orders = $orders->orderBy('donhang.TrangThai', 'asc')->paginate(10);
        $shipers = User::where('VaiTro', 3)->get();
        $viewData = [
            'orders' => $orders,
            'status' => $status,
            'shipers' => $shipers,
            'menu' => $menu,
            'query'  => $request->query()
        ];

        return View('backend.order.index', $viewData);
    }

    public function show($id) {
        $orders = Order_Detail::with('product')->where('id_DH', $id)->get();
        return View('backend.order.show',compact('orders'));
    }

    public function pack($status_order) {
        $status = Order::STATUS_ORDER;
        $query = Order::with('user:id,Ten,DiaChi,SDT')->whereNotNull('id_NV')->whereNull('XacNhan');

        switch ($status_order) {
            case 0:
                $query->where('TrangThai', 0);
                break;
            case 1:
                $query->where('TrangThai', 1);
                break;
            case 3:
                $query->where('TrangThai', 3);
                break;
            case 4:
                $query->where('TrangThai', 4);
                break;
            case 5:
                $query->where('TrangThai', 5);
                break;
        }

        $orders = $query->orderBy('id', 'asc')->paginate(10);
        return View('backend.order.pack',compact('orders', 'status', 'status_order'));
    }

    public function deliver($status_order) {
        if (in_array($status_order, [1,2,3,4,5])) {
            $status = Order::STATUS_ORDER;

            $query = Order::query();
            $query->with('user:id,Ten,DiaChi,SDT');
            $query->where('id_NV', \Auth::user()->id);
            if ($status_order == 5) {
                $query->whereIn('donhang.TrangThai', [4,5]);
            } elseif ($status_order == 1) {
                $query->whereIn('donhang.TrangThai', [1,2]);
            } else {
                $query->where('donhang.TrangThai', $status_order);
            }
            $query->orderBy('donhang.TrangThai', 'asc');
            $orders = $query->paginate(10);
            return View('backend.order.deliver',compact('orders', 'status', 'status_order'));
        }
    }

    public function updateShiper(Request $request, $id)
    {
        if($request->ajax()) {
            $order = Order::find($id);
            $order->id_NV = $request->shiperId;
            $order->NgayGiao = date("Y-m-d");
            $order->save();

            return response([
                'code' => 1
            ]);
        }
    }

    public function cancel($order_id)
    {
        Order::find($order_id)->update(['TrangThai'=> 4]);
        $orderDetails = Order_Detail::where('id_DH', $order_id)->get();
        if (!$orderDetails->isEmpty()) {
            foreach($orderDetails as $orderDet) {
                $product = Product::find($orderDet->product_id);
                $product->update(['TongTien' => $product->quantities + $orderDet->quantities]);
            }
        }

        return redirect()->back();
    }

    public function updateStatus(Request $request, $id)
    {
        if($request->ajax()) {
            $order = Order::find($id);
            if($request->status == 4 || $request->status == 5) {
                $orderDetails = Order_Detail::where('id_DH', $id)->get();
                if (!$orderDetails->isEmpty()) {
                    foreach($orderDetails as $orderDet) {
                        $product = Product::find($orderDet->id_SP);
                        $product->update(['SoLuong' => $product->SoLuong + $orderDet->SoLuong]);
                    }
                }
            }
            $order->TrangThai = $request->status;
            $order->NgayGiao = date("Y-m-d");
            $order->save();

            return response([
                'code' => 1
            ]);
        }
    }

    public function destroy($id)
    {
        \DB::beginTransaction();
        try {
            Order::find($id)->delete();
            \DB::commit();
            return redirect()->back();
        } catch (\Exception $ex) {
            \DB::rollback();
            return redirect()->back();
        }
    }

    public function updateConfirm(Request $request, $id)
    {
        \DB::beginTransaction();
        try {
            Order::find($id)->update([
                'XacNhan' => 1
            ]);
            \DB::commit();
            return redirect()->back();
        } catch (\Exception $ex) {
            \DB::rollback();
            return redirect()->back();
        }
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class OrderController extends Controller
{
    //
}

resources/views/backend/order/create.blade.php
@extends('backend.layouts.app')
@section('title') Người dùng @endsection
@section('content')
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Tạo mới</h3>

            </div>
            <div class="card-body">
                <form method="POST" action="{{route('user.store')}}" accept-charset="UTF-8" class="form-horizontal">
                    @csrf
                    <div class="form-group row">
                        <label for="name" class="col-sm-2 col-form-label">Tên <span class="note">*</span></label>

                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="name" id="name" value="{{old('name')}}">
                            @if ($errors && $errors->has('name'))
                                <p class="text-danger text-xs error-message">{{ $errors->first('name') }}</p>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="email" class="col-sm-2 col-form-label">Email <span class="note">*</span></label>

                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="email" id="email" value="{{old('email')}}">
                            @if ($errors && $errors->has('email'))
                                <p class="text-danger text-xs error-message">{{ $errors->first('email') }}</p>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="password" class="col-sm-2 col-form-label">Password <span class="note">*</span></label>

                        <div class="col-sm-4">
                            <input type="password" class="form-control" name="password" id="password" value="{{old('password')}}">
                            @if ($errors && $errors->has('password'))
                                <p class="text-danger text-xs error-message">{{ $errors->first('password') }}</p>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="address" class="col-sm-2 col-form-label">Địa chỉ </label>

                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="address" id="address" value="{{old('address')}}">
                            @if ($errors && $errors->has('address'))
                                <p class="text-danger text-xs error-message">{{ $errors->first('address') }}</p>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="phone_number" class="col-sm-2 col-form-label">Số điện thoại</label>

                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="phone_number" id="phone_number" value="{{old('phone_number')}}">
                            @if ($errors && $errors->has('phone_number'))
                                <p class="text-danger text-xs error-message">{{ $errors->first('phone_number') }}</p>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Vai trò</label>
                        <div class="input-group date col-sm-4">
                            <select name="role" id="role" value="{{old('role')}}" class="form-control">
                                @foreach($roleUser as $key=>$role)
                                    <option value="{{$key}}">{{$role}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Hiển thị</label>

                        <div class="col-sm-10">
                            <input name="active" type="checkbox" id="active" />
                        </div>
                    </div>

                    <!-- <div class="form-group row"> -->
                        <div class="form-group row">
                            <div class="col-sm-2">
                            </div>
                            <div class="col-sm-1">
                                <button class="btn btn-default float-left"><a style="color:black" href="{{ route('user.index') }}">Hủy</a></button>
                            </div>
                            <div class="col-sm-1">
                                <button type="submit" class="btn btn-info">Tạo mới</button>
                            </div>
                        </div>
                    <!-- </div> -->
                </form>
            </div>
        </div>
        <!-- /.card -->
    </section>
@endsection

resources/views/backend/order/deliver.blade.php
@extends('backend.layouts.app')
@section('title') Danh sách đơn hàng @endsection
@section('content')
    <section class="content">
        <div class="container-fluid">
            <!-- Main row -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <!-- /.card-header -->
                        <div class="card-header">
                            <h3 class="card-title">
                            @if($status_order == 1)
                                Danh sách đơn hàng cần giao
                            @elseif($status_order == 3)
                                Danh sách đơn hàng đã giao
                            @else
                                Danh sách đơn hàng khách không nhận
                            @endif
                            </h3>
                        </div>
                        <div class="card-body table-responsive p-0">
                            <table class="table table-hover text-nowrap">
                                <thead>
                                <tr>
                                    {{--<th>Stt</th>--}}
                                    <th>ID</th>
                                    <th>Tên KH</th>
                                    <th style="width: 200px !important;">Địa chỉ</th>
                                    <th>Số điện thoại</th>
                                    <th>Tổng tiền</th>
                                    <th>Chi tiết</th>
                                    <th>Ngày tạo</th>
                                    <th>Trạng thái</th>
                                    <th>Người giao</th>
                                    <th>Hóa đơn</th>
                                </tr>
                                </thead>
                                <tbody>
                                @if (!$orders->isEmpty())
                                    @php $i = 1 @endphp
                                    @foreach($orders as $item)
                                        <tr>
                                            {{--<td>{{ $i }}</td>--}}
                                            <td>{{ $item->id }}</td>
                                            <td>{{ $item->user->Ten ?? "" }}</td>
                                            <td style="width: 200px !important;">
                                                <p>
                                                    {{ isset($item->user->DiaChi)? $item->user->DiaChi :  $item->user->DiaChi}}
                                                </p>
                                            </td>
                                            <td>{{ isset($item->user->SDT)? $item->user->SDT :  $item->user->SDT}}</td>
                                            <td>{{ number_format($item->TongTien,0,',','.') }} VNĐ</td>
                                            <td><a target="_blank" href="{{ route('order.show', $item->id) }}">Chi tiết</a></td>
                                            <td>{{ $item->NgayTao }}</td>
                                            <td>
                                                @if($status_order == 1 || $status_order == 2)
                                                    <select name="status_order" class="update_status_order">
                                                        @foreach($status as $key => $value)
                                                            @if($status_order == 1 && ($key == 1 || $key == 2 || $key == 3|| $key == 5))
                                                                <option value="{{ $key }}" {{ $item->TrangThai == $key ? 'selected="selected"' : '' }}>{{ $value }}</option>
                                                            @endif
                                                        @endforeach
                                                    </select>
                                                    <button type="button" class="btn btn-primary btn-xs btn-change-status" style="width: 50px" url="{{ route('order.update.status', $item->id) }}" >Lưu</button>
                                                @else 
                                                    <div style="color:red"> {{$status[$status_order]}}</div>
                                                @endif
                                            </td>

                                            <td>
                                                {{ $item->user_shiper->Ten ?? "" }}
                                            </td>
                                            <td class="billing"><a href="{{route('billing', $item->id)}}" title="Hóa đơn"><i class="fas fa-file-alt"></i></a></td>
                                        </tr>
                                        @php $i++ @endphp
                                    @endforeach
                                 @endif
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                        @if($orders->hasPages())
                          <div class="pagination text-center mb-4">
                            {{ $orders->links() }}
                          </div>
                        @endif
                    </div>
                    <!-- /.card -->
                </div>
            </div>
            <!-- /.row (main row) -->
        </div><!-- /.container-fluid -->
    </section>
    @include('backend.common.modal_delete', ['messageConfirm' => 'Bạn có muốn xóa'])
@endsection
@section('js-custom.script')
    <script>
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $(function () {
            $('.btn-change-status').click(function () {
                var url = $(this).attr('url');
                var status = $(this).parent().find('.update_status_order').val();

                $.ajax({
                    url: url,
                    method: 'POST',
                    type:'json',
                    data: {
                        status : status,
                    }
                }).done(function( results ) {
                    console.log(results)
                    alert('Cập nhật trạng thái thành công !!!')
                    var curentUrrl = window.location.href;
                    window.location.href = curentUrrl
                }).fail(function( jqXHR, textStatus ) {
                    console.log(jqXHR)
                });
            });
        })
    </script>
@endsection

resources/views/backend/order/edit.blade.php
@extends('backend.layouts.app')
@section('title') Người dùng @endsection
@section('content')
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Chỉnh sửa</h3>

            </div>
            <div class="card-body">
                <form method="POST" action="{{route('user.update',$user->id)}}" accept-charset="UTF-8" class="form-horizontal">
                    @csrf
                    @method('PATCH')
                    <div class="form-group row">
                        <label for="name" class="col-sm-2 col-form-label">Tên <span class="note">*</span></label>

                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="name" id="name" value="{{ $user->name }}">
                            @if ($errors && $errors->has('name'))
                                <p class="text-danger text-xs error-message">{{ $errors->first('name') }}</p>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="email" class="col-sm-2 col-form-label">Email <span class="note">*</span></label>

                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="email" id="email" value="{{ $user->email }}">
                            @if ($errors && $errors->has('email'))
                                <p class="text-danger text-xs error-message">{{ $errors->first('email') }}</p>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="password" class="col-sm-2 col-form-label">Password <span class="note">*</span></label>

                        <div class="col-sm-4">
                            <input type="password" class="form-control" name="password" id="password" value="{{ $user->password }}">
                            @if ($errors && $errors->has('password'))
                                <p class="text-danger text-xs error-message">{{ $errors->first('password') }}</p>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="address" class="col-sm-2 col-form-label">Địa chỉ </label>

                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="address" id="address" value="{{ $user->address }}">
                            @if ($errors && $errors->has('address'))
                                <p class="text-danger text-xs error-message">{{ $errors->first('address') }}</p>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="phone_number" class="col-sm-2 col-form-label">Số điện thoại</label>

                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="phone_number" id="phone_number" value="{{ $user->phone_number }}">
                            @if ($errors && $errors->has('phone_number'))
                                <p class="text-danger text-xs error-message">{{ $errors->first('phone_number') }}</p>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Vai trò</label>
                        <div class="input-group date col-sm-4">
                            <select name="role" id="role" value="{{ $user->role }}" class="form-control">
                                @foreach($roleUser as $key=>$role)
                                    @if($key == $user->role)
                                        <option value="{{ $key }}" selected="selected">{{ $role }}</option>
                                    @else
                                        <option value="{{ $key }}">{{ $role }}</option>
                                    @endif
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Hiển thị</label>

                        <div class="col-sm-10">
                            <input name="active" type="checkbox" id="active" {{ $user->active == 1 ? 'checked' : ''}}/>
                        </div>
                    </div>

                    <input type="hidden" name="user_id" value="{{ $user->id }}">

                    <div class="form-group row">
                        <div class="col-sm-2">
                        </div>
                        <div class="col-sm-1">
                            <button class="btn btn-default float-left"><a style="color:black" href="{{ route('user.index') }}">Hủy</a></button>
                        </div>
                        <div class="col-sm-1">
                            <button type="submit" class="btn btn-info">Tạo mới</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <!-- /.card -->
    </section>
@endsection