routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Auth','prefix' => 'thanh-vien'], function(){
    Route::get('dang-ky','RegisterController@getFormRegister')->name('get.user.register'); // đăng ký
    Route::post('dang-ky','RegisterController@postRegister')->name('post.user.register'); // xử lý đăng ký

    Route::get('dang-nhap','LoginController@getFormLogin')->name('get.user.login'); // đăng nhập
    Route::post('dang-nhap','LoginController@postLogin')->name('post.user.login'); // xử lý đăng nhập

    Route::get('dang-xuat','LoginController@getLogout')->name('get.user.logout'); // đăng xuất

});


Route::get('/', 'HomeController@index')->name('client.home');
Route::get('/product/{id}', 'ProductController@detail')->name('client.product_detail');
Route::get('/contact', 'ContactController@create')->name('client.contact_create');
Route::post('contact', 'ContactController@store')->name('post.contact');
Route::get('/about', 'PageController@about')->name('client.about');
Route::get('/shopping-guide', 'PageController@shoppingGuide')->name('client.shopping_guide');
Route::get('/policy', 'PageController@policy')->name('client.policy');
Route::get('/login', 'LoginController@create')->name('client.login_create');
Route::get('/category_product/{id}', 'ProductCategoryController@detail')->name('client.category_producte_detail');
Route::get('search', 'HomeController@search')->name('client.search');
Route::get('/info/user', 'InfoUserController@index')->name('info.user');
Route::post('/update/info/user', 'InfoUserController@updateInfoUser')->name('update.info.user');
Route::get('list/order/transported', 'InfoUserController@listOrderTransported')->name('list.order.transported');
Route::get('cancel/order/{id}', 'InfoUserController@cancelOrder')->name('cancel.order');
Route::get('list/order/success', 'InfoUserController@listOrderSuccess')->name('list.order.success');
Route::get('/billing/{id}', 'BillingController@billing')->name('billing');
Route::get('/change/password', 'InfoUserController@getFormChangePasswor')->name('change.password');
Route::post('/change/password', 'InfoUserController@changePassword')->name('change.password');

Route::get('don-hang.html','ShoppingCartController@index')->name('get.shopping.list'); // gio hang
Route::prefix('shopping')->group(function () {
    Route::get('add/{id}','ShoppingCartController@add')->name('get.shopping.add'); // thêm giỏ hàng
    Route::get('delete/{id}','ShoppingCartController@delete')->name('get.shopping.delete'); // xoá sp trong gi hàng
    Route::get('update/{id}','ShoppingCartController@update')->name('ajax_get.shopping.update'); // cập nhật
    Route::get('info/payment', 'ShoppingCartController@getFromPayment')->name('get.info.payment');
    Route::post('pay','ShoppingCartController@saveOrder')->name('post.shopping.pay'); // xử lý giỏ hàng lưu thông tin
    Route::get('delete-all','ShoppingCartController@deleteAll')->name('get.shopping.delete_all'); // xử lý giỏ hàng lưu thông tin
});

Route::namespace('Admin')->prefix('admin')->middleware(['auth'])->group(function () {
    Route::middleware(['is_admin'])->group(function () {
        Route::get('/', 'DashboardController@index')->name('admin.dashboard');
        Route::resource('product', 'ProductController')->except(['show']);
        Route::resource('order', 'OrdersController');
        Route::get('order/pack/{flg}', 'OrdersController@pack')->name('order.pack');
        Route::get('order/deliver/{status}', 'OrdersController@deliver')->name('order.deliver');
        Route::delete('order/cancel/{order_id}', 'OrdersController@cancel')->name('order.cancel');
        Route::post('update/shiper/{id}', 'OrdersController@updateShiper')->name('order.shiper.status');
        Route::post('update/status/{id}', 'OrdersController@updateStatus')->name('order.update.status');
        Route::resource('category_product', 'CategoryProductController')->except(['show']);
        Route::resource('supplier', 'SuppliersController')->except(['show']);
        Route::resource('information', 'InformationsController')->except(['show']);
        Route::resource('user', 'UsersController')->except(['show']);
        Route::get('/contact', 'ContactsController@index')->name('contact.index');
        Route::delete('contact/destroy/{id}', 'ContactsController@destroy')->name('contact.destroy');
        Route::get('update/confirm/{id}', 'OrdersController@updateConfirm')->name('order.update.confirm');
    });
    Route::middleware(['is_role_access'])->group(function () {
        Route::resource('order', 'OrdersController')->except(['show']);
    });
});
Auth::routes(['register' => false]);
Route::get('/logout', 'Auth\LoginController@logout')->name('auth.logout');
Route::get('admin/logout', 'Auth\LoginController@logoutAdmin')->name('auth.admin.logout');
Route::post('admin/login', 'Auth\LoginController@postAdminLogin')->name('auth.admin.login');
Route::get('/home', 'HomeController@index')->name('home');

resources/views/backend/layouts/app.blade.php
<!DOCTYPE html>
<html>
<!-- header s -->
@include('backend.layouts.header')
<!-- header end -->
<body class="hold-transition sidebar-mini layout-fixed">
	<div class="wrapper">
		<!-- nav s -->
		@include('backend.layouts.nav')
		<!-- nav e -->
		<!-- menu s -->
		@include('backend.layouts.menu')
		<!-- menu e -->
		<!-- Content s -->
		<div class="content-wrapper" style="margin-left: 300px">
			@yield('content')
		</div>
		<!-- Content e -->
		<!-- Control Sidebar -->
		<aside class="control-sidebar control-sidebar-dark">
		<!-- Control sidebar content goes here -->
		</aside>
		<!-- /.control-sidebar -->
		<!-- footer s -->
		@include('backend.layouts.footer')
		<!-- footer e -->
	</div>
	<!-- script s -->
	@include('backend.layouts.script')
	<!-- script e -->
</body>
</html>

resources/views/backend/layouts/footer.blade.php
<footer class="main-footer" style="margin-left: 300px">
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.0.5
    </div>
  </footer>

resources/views/backend/layouts/header.blade.php
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <title>@yield('title')</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  @include('backend.layouts.style')
</head>

resources/views/backend/layouts/menu.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4" style="width:300px !important">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
        <img src="{{ asset('backend_asset/img/AdminLTELogo.png') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">AllStore</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ asset('backend_asset/img/user2-160x160.jpg') }}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{Auth::user()->Ten}}</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" VaiTro="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->

                @if(Auth::user()->VaiTro == 1)
                    <li class="nav-item has-treeview">
                        <a href="{{ route('category_product.index') }}" class="nav-link">
                            <i class="fas fa-tachometer-alt"></i>
                            <p>Cập nhật thể loại sản phẩm</p>
                        </a>
                    </li>

                    <li class="nav-item has-treeview">
                        <a href="{{ route('product.index') }}" class="nav-link">
                            <i class="fas fa-tachometer-alt"></i>
                            <p>
                                Cập nhật sản phẩm
                            </p>
                        </a>
                    </li>
                @endif
                @if(Auth::user()->VaiTro == 2)
                    <li class="nav-item has-treeview">
                        <a href="{{ route('order.pack', 0) }}" class="nav-link">
                            <i class="fas fa-tachometer-alt"></i>
                            <p>
                                Xem đơn đặt hàng cần đóng gói
                            </p>
                        </a>
                    </li>
                    <li class="nav-item has-treeview">
                        <a href="{{ route('order.pack', 1) }}" class="nav-link">
                            <i class="fas fa-tachometer-alt"></i>
                            <p>
                                Xem đơn đặt hàng đã đóng gói
                            </p>
                        </a>
                    </li>
                    <li class="nav-item has-treeview">
                        <a href="{{ route('order.pack', 5) }}" class="nav-link">
                            <i class="fas fa-tachometer-alt"></i>
                            <p>
                                Xem đơn hàng khách không nhận
                            </p>
                        </a>
                    </li>
                    <li class="nav-item has-treeview">
                        <a href="{{ route('order.pack', 3) }}" class="nav-link">
                            <i class="fas fa-tachometer-alt"></i>
                            <p>
                                Xem danh sách đơn hàng đã giao
                            </p>
                        </a>
                    </li>
                @elseif(Auth::user()->VaiTro == 1)
                    <li class="nav-item has-treeview">
                        <a href="{{ route('order.index') }}" class="nav-link">
                            <i class="fas fa-tachometer-alt"></i>
                            <p>
                                Xử lý đơn hàng
                            </p>
                        </a>
                    </li>
                    <li class="nav-item has-treeview">
                        <a href="{{ route('order.index', ['menu' => 'success']) }}" class="nav-link">
                            <i class="fas fa-tachometer-alt"></i>
                            <p>
                                Xem danh sách đơn hàng
                            </p>
                        </a>
                    </li>
                @elseif(Auth::user()->VaiTro == 3)
                    <li class="nav-item has-treeview">
                        <a href="{{ route('order.deliver', 1) }}" class="nav-link">
                            <i class="fas fa-tachometer-alt"></i>
                            <p>
                                Xem đơn hàng cần giao
                            </p>
                        </a>
                    </li>
                    <li class="nav-item has-treeview">
                        <a href="{{ route('order.deliver', 3) }}" class="nav-link">
                            <i class="fas fa-tachometer-alt"></i>
                            <p>
                                Xem đơn hàng đã giao
                            </p>
                        </a>
                    </li>
                    <li class="nav-item has-treeview">
                        <a href="{{ route('order.deliver', 5)}}" class="nav-link">
                            <i class="fas fa-tachometer-alt"></i>
                            <p>
                                Xem đơn hàng khách không nhận
                            </p>
                        </a>
                    </li>                    
                @endif
                @if(Auth::user()->VaiTro == 1)
                    <li class="nav-item has-treeview">
                        <a href="{{ route('user.index') }}" class="nav-link">
                            <i class="fas fa-tachometer-alt"></i>
                            <p>
                                Quản lý người dùng
                            </p>
                        </a>
                    </li>
                    <li class="nav-item has-treeview">
                        <a href="{{ route('supplier.index') }}" class="nav-link">
                            <i class="fas fa-tachometer-alt"></i>
                            <p>
                                Cập nhật nhà cung cấp
                            </p>
                        </a>
                    </li>
                    <li class="nav-item has-treeview">
                        <a href="{{ route('contact.index') }}" class="nav-link">
                            <i class="fas fa-tachometer-alt"></i>
                            <p>
                                Xem liên hệ
                            </p>
                        </a>
                    </li>
                    <li class="nav-item has-treeview">
                        <a href="{{ route('information.index') }}" class="nav-link">
                            <i class="fas fa-tachometer-alt"></i>
                            <p>
                                Cập nhật thông tin Shop
                            </p>
                        </a>
                    </li>
                    <li class="nav-item has-treeview">
                        <a href="{{ route('product.create') }}" class="nav-link">
                            <i class="fas fa-tachometer-alt"></i>
                            <p>
                                Nhập Hàng
                            </p>
                        </a>
                    </li>
                @endif
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

resources/views/backend/layouts/nav.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <!-- <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a -->>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      @if(\Auth::user()->VaiTro == 1)
        <a href="{{ route('product.index') }}" class="nav-link"></a>
      @elseif(\Auth::user()->VaiTro == 2)
        <a href="{{ route('order.pack', 0) }}" class="nav-link"></a>
      @else 
        <a href="{{ route('order.deliver', 1) }}" class="nav-link"></a>
      @endif
    </li>
  </ul>
<!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <!-- Notifications Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="fas fa-user-circle"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <a href="{{ route('auth.admin.logout') }}" class="dropdown-item">
          <i class="fas fa-sign-out-alt"></i> &nbsp; Logout
        </a>
      </div>
    </li>
  </ul>
</nav>

resources/views/backend/layouts/script.blade.php
<!-- jQuery -->
<script src="{{ asset('backend_asset/plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap -->
<script src="{{ asset('backend_asset/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE -->
<script src=" {{ asset('backend_asset/js/adminlte.js') }}"></script>
<script src=" {{ asset('backend_asset/plugins/select2/dist/js/select2.js') }}"></script>
<!-- OPTIONAL SCRIPTS -->
<script src=" {{ asset('backend_asset/js/main.js') }}"></script>
<script>
    $(function () {
        $(".input_select2") .select2();
    })
</script>
@yield('js-custom.script')

resources/views/backend/layouts/style.blade.php
<!-- Font Awesome -->
<link rel="stylesheet" href="{{ asset('backend_asset/plugins/fontawesome-free/css/all.min.css') }}">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<!-- Theme style -->
<link rel="stylesheet" href="{{ asset('backend_asset/css/adminlte.min.css') }}">
<link rel="stylesheet" href="{{ asset('backend_asset/plugins/select2/dist/css/select2.min.css') }}">
<!-- Google Font: Source Sans Pro -->
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
<link rel="stylesheet" href="{{ asset('backend_asset/css/custom.css') }}">
<!-- custom style -->
@yield('css-custom.style')