routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Auth','prefix' => 'thanh-vien'], function(){
    Route::get('dang-ky','RegisterController@getFormRegister')->name('get.user.register'); // đăng ký
    Route::post('dang-ky','RegisterController@postRegister')->name('post.user.register'); // xử lý đăng ký

    Route::get('dang-nhap','LoginController@getFormLogin')->name('get.user.login'); // đăng nhập
    Route::post('dang-nhap','LoginController@postLogin')->name('post.user.login'); // xử lý đăng nhập

    Route::get('dang-xuat','LoginController@getLogout')->name('get.user.logout'); // đăng xuất

});


Route::get('/', 'HomeController@index')->name('client.home');
Route::get('/product/{id}', 'ProductController@detail')->name('client.product_detail');
Route::get('/contact', 'ContactController@create')->name('client.contact_create');
Route::post('contact', 'ContactController@store')->name('post.contact');
Route::get('/about', 'PageController@about')->name('client.about');
Route::get('/shopping-guide', 'PageController@shoppingGuide')->name('client.shopping_guide');
Route::get('/policy', 'PageController@policy')->name('client.policy');
Route::get('/login', 'LoginController@create')->name('client.login_create');
Route::get('/category_product/{id}', 'ProductCategoryController@detail')->name('client.category_producte_detail');
Route::get('search', 'HomeController@search')->name('client.search');
Route::get('/info/user', 'InfoUserController@index')->name('info.user');
Route::post('/update/info/user', 'InfoUserController@updateInfoUser')->name('update.info.user');
Route::get('list/order/transported', 'InfoUserController@listOrderTransported')->name('list.order.transported');
Route::get('cancel/order/{id}', 'InfoUserController@cancelOrder')->name('cancel.order');
Route::get('list/order/success', 'InfoUserController@listOrderSuccess')->name('list.order.success');
Route::get('/billing/{id}', 'BillingController@billing')->name('billing');
Route::get('/change/password', 'InfoUserController@getFormChangePasswor')->name('change.password');
Route::post('/change/password', 'InfoUserController@changePassword')->name('change.password');

Route::get('don-hang.html','ShoppingCartController@index')->name('get.shopping.list'); // gio hang
Route::prefix('shopping')->group(function () {
    Route::get('add/{id}','ShoppingCartController@add')->name('get.shopping.add'); // thêm giỏ hàng
    Route::get('delete/{id}','ShoppingCartController@delete')->name('get.shopping.delete'); // xoá sp trong gi hàng
    Route::get('update/{id}','ShoppingCartController@update')->name('ajax_get.shopping.update'); // cập nhật
    Route::get('info/payment', 'ShoppingCartController@getFromPayment')->name('get.info.payment');
    Route::post('pay','ShoppingCartController@saveOrder')->name('post.shopping.pay'); // xử lý giỏ hàng lưu thông tin
    Route::get('delete-all','ShoppingCartController@deleteAll')->name('get.shopping.delete_all'); // xử lý giỏ hàng lưu thông tin
});

Route::namespace('Admin')->prefix('admin')->middleware(['auth'])->group(function () {
    Route::middleware(['is_admin'])->group(function () {
        Route::get('/', 'DashboardController@index')->name('admin.dashboard');
        Route::resource('product', 'ProductController')->except(['show']);
        Route::resource('order', 'OrdersController');
        Route::get('order/pack/{flg}', 'OrdersController@pack')->name('order.pack');
        Route::get('order/deliver/{status}', 'OrdersController@deliver')->name('order.deliver');
        Route::delete('order/cancel/{order_id}', 'OrdersController@cancel')->name('order.cancel');
        Route::post('update/shiper/{id}', 'OrdersController@updateShiper')->name('order.shiper.status');
        Route::post('update/status/{id}', 'OrdersController@updateStatus')->name('order.update.status');
        Route::resource('category_product', 'CategoryProductController')->except(['show']);
        Route::resource('supplier', 'SuppliersController')->except(['show']);
        Route::resource('information', 'InformationsController')->except(['show']);
        Route::resource('user', 'UsersController')->except(['show']);
        Route::get('/contact', 'ContactsController@index')->name('contact.index');
        Route::delete('contact/destroy/{id}', 'ContactsController@destroy')->name('contact.destroy');
        Route::get('update/confirm/{id}', 'OrdersController@updateConfirm')->name('order.update.confirm');
    });
    Route::middleware(['is_role_access'])->group(function () {
        Route::resource('order', 'OrdersController')->except(['show']);
    });
});
Auth::routes(['register' => false]);
Route::get('/logout', 'Auth\LoginController@logout')->name('auth.logout');
Route::get('admin/logout', 'Auth\LoginController@logoutAdmin')->name('auth.admin.logout');
Route::post('admin/login', 'Auth\LoginController@postAdminLogin')->name('auth.admin.login');
Route::get('/home', 'HomeController@index')->name('home');

app/Supplier.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Supplier extends Model
{
    public $table = "nhacungcap";
    public $timestamps = false;
}

app/Http/Controllers/Admin/SuppliersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\SupplierStoreRequest;
use App\Http\Requests\SupplierUpdateRequest;
use App\Supplier;
use DB;

class SuppliersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if (isset($request->name)) {
            $suppliers = Supplier::where('nhacungcap.Ten', 'like', '%' . trim($request->name) . '%')->paginate(6);
        } else {
            $suppliers = Supplier::paginate(6);
        }

        return View('backend.supplier.index',compact('suppliers', 'request'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return View('backend.supplier.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SupplierStoreRequest $request)
    {
        $supplierModel               = new Supplier();
        $supplierModel->Ten         = $request->name;
        $supplierModel->DiaChi      = $request->name;
        $supplierModel->SDT    = $request->phone_number;
        $supplierModel->email        = $request->email;
        $supplierModel->timestamps = false;
        try {
            $supplierModel->save();
            return redirect()->route('supplier.index');
        } catch (Exception $e) {
            die($e->getMessage());
        }
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //lấy tất cả danh mục ứng với id
        $supplier   = Supplier::find($id);
        return View('backend.supplier.edit',compact('supplier'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SupplierUpdateRequest $request, $id)
    {
        $supplier               = Supplier::find($id);
        $supplier->Ten         = $request->name;
        $supplier->DiaChi      = $request->address;
        $supplier->SDT = $request->phone_number;
        $supplier->email        = $request->email;
        $supplier->timestamps = false;

        try {
            $supplier->save();
            return redirect()->route('supplier.index');
        } catch (Exception $e) {
            die($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::beginTransaction();
        try {
            Supplier::find($id)->delete();

            DB::commit();
            return redirect()->route('supplier.index');
        } catch (\Exception $ex) {
            DB::rollback();
            return redirect()->route('supplier.index');
        }
    }
}

resources/views/backend/supplier/create.blade.php
@extends('backend.layouts.app')
@section('title') Danh mục nhà cung cấp @endsection
@section('content')
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Thêm mới</h3>

            </div>
            <div class="card-body">
                <form method="POST" action="{{route('supplier.store')}}" accept-charset="UTF-8" class="form-horizontal">
                    @csrf
                    <div class="form-group row">
                        <label for="name" class="col-sm-2 col-form-label">Tên <span class="note">*</span></label>

                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="name" id="name" value="{{old('name')}}">
                            @if ($errors && $errors->has('name'))
                                <p class="text-danger text-xs error-message">{{ $errors->first('name') }}</p>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="address" class="col-sm-2 col-form-label">Địa chỉ <span class="note">*</span></label>

                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="address" id="address" value="{{old('address')}}">
                            @if ($errors && $errors->has('address'))
                                <p class="text-danger text-xs error-message">{{ $errors->first('address') }}</p>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="phone_number" class="col-sm-2 col-form-label">Số điện thoại <span class="note">*</span></label>

                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="phone_number" id="phone_number" value="{{old('phone_number')}}">
                            @if ($errors && $errors->has('phone_number'))
                                <p class="text-danger text-xs error-message">{{ $errors->first('phone_number') }}</p>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="email" class="col-sm-2 col-form-label">Email <span class="note">*</span></label>

                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="email" id="email" value="{{old('email')}}">
                            @if ($errors && $errors->has('email'))
                                <p class="text-danger text-xs error-message">{{ $errors->first('email') }}</p>
                            @endif
                        </div>
                    </div>

                    <!-- <div class="form-group row"> -->
                        <div class="form-group row">
                            <div class="col-sm-2">
                            </div>
                            <div class="col-sm-1">
                                <button class="btn btn-default float-left"><a style="color:black" href="{{ route('supplier.index') }}">Hủy</a></button>
                            </div>
                            <div class="col-sm-2">
                                <button type="submit" class="btn btn-info">Tạo mới</button>
                            </div>
                        </div>
                    <!-- </div> -->
                </form>
            </div>
        </div>
        <!-- /.card -->
    </section>
@endsection

resources/views/backend/supplier/edit.blade.php
@extends('backend.layouts.app')
@section('title') Chỉnh sửa nhà cung cấp @endsection
@section('content')
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Chỉnh sửa</h3>

            </div>
            <div class="card-body">
                <form method="POST" action="{{route('supplier.update',$supplier->id)}}" accept-charset="UTF-8" class="form-horizontal">
                    @csrf
                    @method('PATCH')
                    <div class="form-group row">
                        <label for="name" class="col-sm-2 col-form-label">Tên <span class="note">*</span></label>

                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="name" id="name" value="{{ $supplier->Ten }}">
                            @if ($errors && $errors->has('name'))
                                <p class="text-danger text-xs error-message">{{ $errors->first('name') }}</p>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="address" class="col-sm-2 col-form-label">Địa chỉ <span class="note">*</span></label>

                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="address" id="address" value="{{ $supplier->DiaChi }}">
                            @if ($errors && $errors->has('address'))
                                <p class="text-danger text-xs error-message">{{ $errors->first('address') }}</p>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="phone_number" class="col-sm-2 col-form-label">Số điện thoại <span class="note">*</span></label>

                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="phone_number" id="phone_number" value="{{ $supplier->SDT }}">
                            @if ($errors && $errors->has('phone_number'))
                                <p class="text-danger text-xs error-message">{{ $errors->first('phone_number') }}</p>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="email" class="col-sm-2 col-form-label">Email <span class="note">*</span></label>

                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="email" id="email" value="{{ $supplier->email }}">
                            @if ($errors && $errors->has('email'))
                                <p class="text-danger text-xs error-message">{{ $errors->first('email') }}</p>
                            @endif
                        </div>
                    </div>

                    <input type="hidden" name="supplier_id" value="{{ $supplier->id }}">

                    <div class="form-group row">
                        <div class="col-sm-2">
                        </div>
                        <div class="col-sm-1">
                            <button class="btn btn-default float-left"><a style="color:black" href="{{ route('supplier.index') }}">Hủy</a></button>
                        </div>
                        <div class="col-sm-2">
                            <button type="submit" class="btn btn-info">Cập nhật</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <!-- /.card -->
    </section>
@endsection

resources/views/backend/supplier/index.blade.php
@extends('backend.layouts.app')
@section('title') Danh sách nhà cung cấp @endsection
@section('content')
    <section class="content">
        <div class="container-fluid">
            <!-- Main row -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <!-- /.card-header -->
                        <div class="card-header">
                            <h3 class="card-title">Danh sách nhà cung cấp</h3>

                            <div class="card-tools">
                                <a class="btn btn-success btn-sm" href="{{ route('supplier.create') }}"><span
                                    class="fas fa-plus"></span> Thêm mới </a>
                            </div>
                            <div class="form-search">
                                <form class="form-inline" action="{{ route('supplier.index') }}" method="get">
                                  <div class="form-row align-items-center margin-auto">
                                    <div class="form-group mr-2 mb-2">
                                      <label for="name" class="sr-only">Tên Nhà cung cấp</label>
                                      <input type="text" name="name" value="{{ $request->get('name') }}" class="form-control" id="name"
                                             placeholder="Tên nhà cung cấp">
                                    </div>
                                    <button type="submit" class="btn-search btn btn-primary mb-2"><span
                                          class="fas fa-search"></span> Tìm kiếm </button>
                                  </div>
                                </form>
                            </div>
                        </div>
                        <div class="card-body table-responsive p-0">
                            <table class="table table-hover text-nowrap ">
                                <thead>
                                <tr>
                                    {{--<th>Stt</th>--}}
                                    <th>ID</th>
                                    <th>Tên</th>
                                    <th>Địa chỉ</th>
                                    <th>Số điện thoại</th>
                                    <th>Email</th>
                                    <th>Hành động</th>
                                </tr>
                                </thead>
                                <tbody>        
                                @if (!$suppliers->isEmpty())
                                    @php $i = $suppliers->firstItem() @endphp
                                    @foreach($suppliers as $sup)
                                        <tr>
                                            {{--<td>{{ $i }}</td>--}}
                                            <td>{{ $sup->id }}</td>
                                            <td>{{ $sup->Ten }}</td>
                                            <td>{{ $sup->DiaChi }}</td>
                                            <td>{{ $sup->SDT }}</td>
                                            <td>{{ $sup->email }}</td>
                                            <td>
                                                <a class="btn btn-primary btn-sm" href="{{ route('supplier.edit', $sup->id) }}">
                                                    <i class="fas fa-pencil-alt"></i>
                                                </a>
                                                <a id="{{$sup->id}}" class="btn btn-danger btn-sm btn-delete" href="#">
                                                    <i class="fas fa-trash"></i>
                                                    <form method="post" action="{{ route('supplier.destroy', $sup->id) }}"
                                                          id="form_{{$sup->id}}">
                                                      @csrf
                                                      @method('DELETE')
                                                    </form>
                                                </a>
                                            </td>
                                        </tr>
                                        @php $i++ @endphp
                                    @endforeach
                                 @endif
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                        @if($suppliers->hasPages())
                          <div class="pagination text-center mb-4">
                            {{ $suppliers->links() }}
                          </div>
                        @endif
                    </div>
                    <!-- /.card -->
                </div>
            </div>
            <!-- /.row (main row) -->
        </div><!-- /.container-fluid -->
    </section>
    @include('backend.common.modal_delete', ['messageConfirm' => 'Bạn có muốn xóa'])
@endsection